### ISSUE TITLE
Spam at console and  doesnt keep inventories and same  set in worlds

### ISSUE THREAD

**Issue by TheHeRoMaN** [Gnat008/perworldinventory-kt#119]
TheHeRoMaN issued server command: /warp skypvp
```java
[15:18:31] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to PerWorldInventory v1.10.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:444) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.earth2me.essentials.Teleport.now(Teleport.java:145) [EssentialsX-2.0.1%20(2).jar:?]
	at com.earth2me.essentials.TimedTeleport$1DelayedTeleportTask.run(TimedTeleport.java:109) [EssentialsX-2.0.1%20(2).jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/attribute/Attribute
	at me.gnat008.perworldinventory.data.players.PWIPlayer.<init>(PWIPlayer.java:94) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerFactory.create(PWIPlayerFactory.java:37) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.addPlayer(PWIPlayerManager.java:118) ~[?:?]
	at me.gnat008.perworldinventory.listeners.player.PlayerTeleportListener.onPlayerTeleport(PlayerTeleportListener.java:51) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	... 13 more
[15:18:31] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to PerWorldInventory v1.10.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:628) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:471) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.earth2me.essentials.Teleport.now(Teleport.java:145) [EssentialsX-2.0.1%20(2).jar:?]
	at com.earth2me.essentials.TimedTeleport$1DelayedTeleportTask.run(TimedTeleport.java:109) [EssentialsX-2.0.1%20(2).jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/attribute/Attribute
	at me.gnat008.perworldinventory.util.Utils.zeroPlayer(Utils.java:73) ~[?:?]
	at me.gnat008.perworldinventory.util.Utils.zeroPlayer(Utils.java:55) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.getPlayerData(PWIPlayerManager.java:164) ~[?:?]
	at me.gnat008.perworldinventory.process.InventoryChangeProcess.processWorldChange(InventoryChangeProcess.java:114) ~[?:?]
	at me.gnat008.perworldinventory.process.InventoryChangeProcess.preProcessWorldChange(InventoryChangeProcess.java:54) ~[?:?]
	at me.gnat008.perworldinventory.listeners.player.PlayerChangedWorldListener.onPlayerChangeWorld(PlayerChangedWorldListener.java:39) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	... 14 more
[15:18:35] [Server thread/INFO]: TheHeRoMaN issued server command: /spawn
[15:18:38] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to PerWorldInventory v1.10.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:444) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.earth2me.essentials.Teleport.now(Teleport.java:130) [EssentialsX-2.0.1%20(2).jar:?]
	at com.earth2me.essentials.TimedTeleport$1DelayedTeleportTask.run(TimedTeleport.java:109) [EssentialsX-2.0.1%20(2).jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/attribute/Attribute
	at me.gnat008.perworldinventory.data.players.PWIPlayer.<init>(PWIPlayer.java:94) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerFactory.create(PWIPlayerFactory.java:37) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.addPlayer(PWIPlayerManager.java:118) ~[?:?]
	at me.gnat008.perworldinventory.listeners.player.PlayerTeleportListener.onPlayerTeleport(PlayerTeleportListener.java:51) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	... 13 more
[15:18:39] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to PerWorldInventory v1.10.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:628) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:471) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.earth2me.essentials.Teleport.now(Teleport.java:130) [EssentialsX-2.0.1%20(2).jar:?]
	at com.earth2me.essentials.TimedTeleport$1DelayedTeleportTask.run(TimedTeleport.java:109) [EssentialsX-2.0.1%20(2).jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/attribute/Attribute
	at me.gnat008.perworldinventory.util.Utils.zeroPlayer(Utils.java:73) ~[?:?]
	at me.gnat008.perworldinventory.util.Utils.zeroPlayer(Utils.java:55) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.getPlayerData(PWIPlayerManager.java:164) ~[?:?]
	at me.gnat008.perworldinventory.process.InventoryChangeProcess.processWorldChange(InventoryChangeProcess.java:114) ~[?:?]
	at me.gnat008.perworldinventory.process.InventoryChangeProcess.preProcessWorldChange(InventoryChangeProcess.java:54) ~[?:?]
	at me.gnat008.perworldinventory.listeners.player.PlayerChangedWorldListener.onPlayerChangeWorld(PlayerChangedWorldListener.java:39) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	... 14 more
[15:18:40] [Server thread/INFO]: [0;31;1m[21mPAC[0;37;1m: [0;32;1mTheHeRoMaN [0;37;22mfailed [0;31;22mPhase [0;37;22mcheck [VL: 1] [Ping: 6] [Info: type:'center' block:'SEA_LANTERN'][m
```

**Comment by BeatlesDev** [comment]
You are using an old version of PWI. Update it to the most recent version.
