### ISSUE TITLE
startup errors

### ISSUE THREAD

**Issue by anemul** [Gnat008/perworldinventory-kt#24]
On start up got a couple of errors , one toward the beginning and the other at the end . This is the Beta 2.0 also .
[latest03082018.log.zip](https://github.com/Gnat008/perworldinventory-kt/files/1795035/latest03082018.log.zip)

**Comment by anemul** [comment]
After joining the server for the first time : 
[16:36:43 WARN]: [PerWorldInventory] Creating a new group on the fly for 'Lobby'. Please double check your `worlds.json` file configuration!
[16:36:43 WARN]: [PerWorldInventory] Creating a new group on the fly for 'swlobby'. Please double check your `worlds.json` file configuration!
[16:36:43 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.0.0 generated an exception while executing task 3402
java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:54) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18) ~[?:?]
	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[16:36:43 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.0.0 generated an exception while executing task 3406
java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:54) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18) ~[?:?]
	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[16:37:00 INFO]: Anemul issued server command: /mv tp lobby
[16:37:08 INFO]: Anemul lost connection: Disconnected
[16:37:08 INFO]: Anemul left the game

**Comment by Gnat008** [comment]
Could you show me your worlds configuration file?

**Comment by anemul** [comment]
[worlds.json.zip](https://github.com/Gnat008/perworldinventory-kt/files/1795205/worlds.json.zip)

**Comment by Gnat008** [comment]
No github, its not ready to be closed. *sigh*

**Comment by Gnat008** [comment]
@anemul if you could download the second release, and tell me if that fixes these issues?

**Comment by anemul** [comment]
I haven't logged in yet , but here is an error that happened about the same place it did last time toward the beggining .
[19:05:03 INFO]: [PerWorldInventory] Enabling PerWorldInventory v2.0.0
[19:05:03 WARN]: [PerWorldInventory] Could not save worlds.json to plugins/PerWorldInventory/worlds.json because worlds.json already exists.
[19:05:03 ERROR]: Error occurred while enabling PerWorldInventory v2.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: co/aikar/timings/lib/TimingManager
	at me.ebonjaeger.perworldinventory.command.acf.BukkitCommandManager.<init>(BukkitCommandManager.java:87) ~[?:?]
	at me.ebonjaeger.perworldinventory.command.acf.PaperCommandManager.<init>(PaperCommandManager.java:33) ~[?:?]
	at me.ebonjaeger.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.kt:105) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ClassNotFoundException: co.aikar.timings.lib.TimingManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	... 14 more

**Comment by Gnat008** [comment]
Hm. Guess those were important after all.

**Comment by anemul** [comment]
and here is what im getting when in game moving from world to world : [19:10:36 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.0.0 generated an exception while executing task 2065
java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:54) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18) ~[?:?]
	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[19:10:36 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.0.0 generated an exception while executing task 2073
java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:54) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18) ~[?:?]
	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[19:10:43 INFO]: Anemul issued server command: /mv tp lobby
[19:10:44 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.0.0 generated an exception while executing task 2150
java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:54) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18) ~[?:?]
	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
>

**Comment by Gnat008** [comment]
@anemul for the startup issue, please re-download. For other issues, make sure it starts up right, then open a different issue.

**Comment by anemul** [comment]
re-downloaded and still getting this :+1: 
[21:39:59 INFO]: [PerWorldInventory] Enabling PerWorldInventory v2.0.0
[21:39:59 WARN]: [PerWorldInventory] Could not save worlds.json to plugins/PerWorldInventory/worlds.json because worlds.json already exists.
[21:40:00 INFO]: [ACF] Minecraft Version: 1.12
[21:40:00 ERROR]: Error occurred while enabling PerWorldInventory v2.0.0 (Is it up to date?)
me.ebonjaeger.perworldinventory.initialization.di.exceptions.InjectorException: Did not find instantiation method for 'interface org.bukkit.plugin.PluginManager'. This class cannot be instantiated; please check the class or your handlers.
	at me.ebonjaeger.perworldinventory.initialization.di.InjectorImpl.findResolutionOrFail(InjectorImpl.java:243) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.InjectorImpl.resolveContext(InjectorImpl.java:153) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.InjectorImpl.resolveDependencies(InjectorImpl.java:186) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.InjectorImpl.resolveContext(InjectorImpl.java:158) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.InjectorImpl.resolve(InjectorImpl.java:133) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.InjectorImpl.getSingleton(InjectorImpl.java:72) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.Injector.getSingleton(Injector.kt:67) ~[?:?]
	at me.ebonjaeger.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.kt:109) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by Gnat008** [comment]
Progress. lol. New version uploaded.

**Comment by anemul** [comment]
[07:41:26 INFO]: [PerWorldInventory] Enabling PerWorldInventory v2.0.0
[07:41:26 WARN]: [PerWorldInventory] Could not save worlds.json to plugins/PerWorldInventory/worlds.json because worlds.json already exists.
[07:41:27 INFO]: [ACF] Minecraft Version: 1.12
[07:41:27 ERROR]: Error occurred while enabling PerWorldInventory v2.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/onarandombox/multiverseinventories/MultiverseInventories
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_161]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_161]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_161]
	at me.ebonjaeger.perworldinventory.initialization.di.utils.ReflectionUtils.safeGetDeclaredMethods(ReflectionUtils.java:165) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.handlers.instantiation.StandardInjectionProvider.validateHasNoInjectMethods(StandardInjectionProvider.java:156) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.handlers.instantiation.StandardInjectionProvider.validateInjection(StandardInjectionProvider.java:142) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.handlers.instantiation.DefaultInjectionProvider.validateInjection(DefaultInjectionProvider.java:37) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.handlers.instantiation.StandardInjectionProvider.safeGet(StandardInjectionProvider.java:43) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.handlers.instantiation.DefaultInjectionProvider.safeGet(DefaultInjectionProvider.java:32) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.handlers.instantiation.DirectInstantiationProvider.resolve(DirectInstantiationProvider.java:19) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.InjectorImpl.findResolutionOrFail(InjectorImpl.java:227) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.InjectorImpl.resolveContext(InjectorImpl.java:153) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.InjectorImpl.resolveDependencies(InjectorImpl.java:186) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.InjectorImpl.resolveContext(InjectorImpl.java:158) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.InjectorImpl.resolve(InjectorImpl.java:133) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.di.InjectorImpl.getSingleton(InjectorImpl.java:72) ~[?:?]
	at me.ebonjaeger.perworldinventory.initialization.Injector.getSingleton(Injector.kt:67) ~[?:?]
	at me.ebonjaeger.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.kt:111) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ClassNotFoundException: com.onarandombox.multiverseinventories.MultiverseInventories
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	... 29 more

**Comment by ljacqu** [comment]
@Gnat008 I think you need to set @NoFieldAccess (or whatever the annotation is called in the injector 😁) onto that class that uses Multiverse stuff. Just like in the java project

**Comment by Gnat008** [comment]
Ah, right. Okay, new beta release. I tested the startup, so now I know it works, so if @anemul can just confirm that... :D

**Comment by anemul** [comment]
Loaded with no errors this time .
