### ISSUE TITLE
In Game 2.0

### ISSUE THREAD

**Issue by anemul** [Gnat008/perworldinventory-kt#25]
[12:11:58 INFO]: Anemul issued server command: /mv tp lobby
[12:11:59 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.0.0 generated an exception while executing task 2072
java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:54) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18) ~[?:?]
	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[12:11:59 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.0.0 generated an exception while executing task 2080
java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:54) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18) ~[?:?]
	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[12:12:06 INFO]: Anemul lost connection: Disconnected
[12:12:07 INFO]: Anemul left the game
[12:12:09 INFO]: UUID of player Anemul is c02cad7a-aaf6-4066-b4a8-b087b594a69f
[12:12:10 INFO]: Anemul[/70.122.71.111:50945] logged in with entity id 2242 at ([Lobby]16.01580157268055, 51.0, -32.27052191323492)
[12:13:04 INFO]: Anemul issued server command: /mv tp Survival
[12:13:05 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.0.0 generated an exception while executing task 2740
java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:54) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18) ~[?:?]
	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[12:13:05 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.0.0 generated an exception while executing task 2746
java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:54) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18) ~[?:?]
	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[12:13:11 INFO]: Anemul issued server command: /mv tp lobby

**Comment by Gnat008** [comment]
Should be fixed in latest.

**Comment by ArhamR** [comment]
I am having the same issue and i have installed installed "perworldinentory-kt-2.1.0"

Latest logs:
https://hasteb.in/duqobiti.md

Plugins (24): LaunchPadPlus, LuckPerms, AdvancedPortals, WorldEdit, WorldBorder, Vault, MassiveCore, WorldGuard, Citizens, ASkyBlock, ChestCommands, Essentials, EssentialsChat, SimpleRename, PerWorldInventory, CommandNPC, EssentialsSpawn, Multiverse-Core, Factions, DiscordSRV, Multiverse-NetherPortals, HolographicDisplays, GriefPrevention, BetterRTP
