### ISSUE TITLE
Version 2.0 no longer saves any inventory....

### ISSUE THREAD

**Issue by Spartan9802** [Gnat008/perworldinventory-kt#28]
Version 2.0 no longer saves any inventory....
Spigot: 1.8.8
Error:
`[12:01:32] [Server thread/ERROR]: Could not pass event PlayerGameModeChangeEvent to PerWorldInventory v2.0.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:753) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at com.onarandombox.MultiverseCore.listeners.MVPlayerListener$2.run(MVPlayerListener.java:353) [Multiverse-Core-2.5.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getStorageContents()[Lorg/bukkit/inventory/ItemStack;
	at me.ebonjaeger.perworldinventory.data.PlayerProfile.<init>(PlayerProfile.kt:47) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileFactory.create(ProfileFactory.kt:21) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager.addPlayerProfile(ProfileManager.kt:44) ~[?:?]
	at me.ebonjaeger.perworldinventory.listener.player.PlayerGameModeChangeListener.onPlayerChangedGameMode(PlayerGameModeChangeListener.kt:40) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	... 12 more`

**Comment by Gnat008** [comment]
I don't believe PWI 2.0 runs on anything under 1.9. Considering 1.13 is around the corner, I'm not exactly inclined to support such an old version, given all of the technical differences between versions. Also the fact that 1.8.x is almost three and a half years old.

**Comment by Spartan9802** [comment]
Thin, could you give you the ability to convert pwi (1.11.3) files to multiverse-inv ?

**Comment by Gnat008** [comment]
@Spartan9802 could you try the latest beta version to see if it works or not?

**Comment by Gnat008** [comment]
*poke*

**Comment by x0Z3ro0x** [comment]
This bug is not relevant. I created a BLANK server with just PWI installed. When I used 2.0 I got the EXACT same error. However the moment I took Gnat008's advice that 2.0 doesn't support anything under 1.9 I grabbed an old PWI jar from bukkit. PerworldInventory 1.5.8 to be exact and the error was NOT able to be replicated. In fact the server booted up normal and PWI worked as planned.

**Comment by Gnat008** [comment]
In order to make PWI 2.0 match the behaviour of 1.x, I changed which method is used to set inventory items, which means (as far as I know, anyway...) that it should work on 1.8.8 servers again. Assuming nothing else is different; Spigot just *loves* random, barely or undocumented breaking changes. I was just trying to get independent verification that this was indeed the case. :)

**Comment by x0Z3ro0x** [comment]
Understood, just wanted to verify this bug for you since the user has not replied to you. Was able to reproduce but your advice fixed the bug. In other words the results I found were that using the correct plugin version for the spigot version being run solved any bugs.

As it stands, this bug is non existent and DOES NOT pose an issue that needs to be fixed. Users just need to use the right version. None the less thank you for making changes for users unwilling to read this far and use the correct version. In the future I have a test server with full remote support JUST for testing bugs. Let me know if you ever want something else tested.
