### ISSUE TITLE
2.0 woes errors in the console 

### ISSUE THREAD

**Issue by anemul** [Gnat008/perworldinventory-kt#29]
[13:46:08 INFO]: Anemul[/70.122.71.111:50739] logged in with entity id 1961 at ([Survival]144.9266191303098, 63.9375, 251.09245269224658)
[13:46:09 WARN]: [PerWorldInventory] Failed to deserialize item in inventory: [ArrayIndexOutOfBoundsException] 37
[13:46:09 WARN]: java.lang.ArrayIndexOutOfBoundsException: 37
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.deserialize(InventorySerializer.kt:71)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:55)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt)
[13:46:09 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[13:46:09 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:46:09 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:46:09 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:46:09 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:46:09 WARN]: [PerWorldInventory] Failed to deserialize item in inventory: [ArrayIndexOutOfBoundsException] 38
[13:46:09 WARN]: java.lang.ArrayIndexOutOfBoundsException: 38
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.deserialize(InventorySerializer.kt:71)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:55)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt)
[13:46:09 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[13:46:09 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:46:09 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:46:09 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:46:09 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:46:09 WARN]: [PerWorldInventory] Failed to deserialize item in inventory: [ArrayIndexOutOfBoundsException] 39
[13:46:09 WARN]: java.lang.ArrayIndexOutOfBoundsException: 39
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.deserialize(InventorySerializer.kt:71)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:55)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt)
[13:46:09 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[13:46:09 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:46:09 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:46:09 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:46:09 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:46:09 WARN]: [PerWorldInventory] Failed to deserialize item in inventory: [ArrayIndexOutOfBoundsException] 40
[13:46:09 WARN]: java.lang.ArrayIndexOutOfBoundsException: 40
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.deserialize(InventorySerializer.kt:71)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:55)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18)
[13:46:09 WARN]: 	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt)
[13:46:09 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[13:46:09 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:46:09 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:46:09 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:46:09 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:46:09 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.0.0 generated an exception while executing task 767
java.lang.IllegalStateException: stats["gamemode"] must not be null
	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:77) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:128) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:80) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$getPlayerData$1.invoke(ProfileManager.kt:18) ~[?:?]
	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$3e3c8424.run(BukkitService.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by Gnat008** [comment]
Is that from existing v1.x data?

**Comment by anemul** [comment]
not sure .

**Comment by Gnat008** [comment]
@anemul Could you try the latest beta version and see if this is resolved?

**Comment by Gnat008** [comment]
Using the latest build, and everything seems to be working fine now.

**Comment by Gnat008** [comment]
Going to close this as it indeed seems to work. If this is in error, please re-open the issue.
