### ISSUE TITLE
IllegalStateException: Using an unstable API that has not been enabled

### ISSUE THREAD

**Issue by mibby** [Gnat008/perworldinventory-kt#33]
PerWorldInventory-KT dev 50
Paper dev 1410 (Spigot 1.12.2)

Testing KT version with PWI 1.x files / conversion.
```
[16:10:33] [Server thread/INFO]: mibby issued server command: /pwi
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] Exception in command: perworldinventory  
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] java.lang.IllegalStateException: Using an unstable API that has not been enabled ( help). See https://acfunstable.emc.gs
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.CommandManager.verifyUnstableAPI(CommandManager.java:493)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.CommandManager.generateCommandHelp(CommandManager.java:163)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.CommandContexts.lambda$new$19(CommandContexts.java:233)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.RegisteredCommand.resolveContexts(RegisteredCommand.java:255)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.RegisteredCommand.resolveContexts(RegisteredCommand.java:191)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.RegisteredCommand.invoke(RegisteredCommand.java:143)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.BaseCommand.executeCommand(BaseCommand.java:467)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.BaseCommand.executeSubcommand(BaseCommand.java:559)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.BaseCommand.execute(BaseCommand.java:376)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.RootCommand.execute(RootCommand.java:69)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.BukkitRootCommand.execute(BukkitRootCommand.java:63)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[16:10:33] [Server thread/ERROR]: [PerWorldInventory] [ACF] 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by Gnat008** [comment]
@mibby could you try the latest beta release [here](https://github.com/Gnat008/perworldinventory-kt/releases/tag/v2.0.0-beta.6) and report if the issue is resolved?

**Comment by Gnat008** [comment]
I have verified that this is indeed fixed.

**Comment by mibby** [comment]
Apologies for the late reply. Seems to be working without error now. Thanks!
