### ISSUE TITLE
Error when serializing potion

### ISSUE THREAD

**Issue by Gnat008** [Gnat008/perworldinventory-kt#39]
```
[14:15:47] [Craft Scheduler Thread - 60/WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.0.0 generated an exception while executing task 477636
java.lang.NullPointerException: null
	at me.ebonjaeger.perworldinventory.serialization.PotionSerializer.serialize(PotionSerializer.kt:39) ~[?:?]
	at me.ebonjaeger.perworldinventory.serialization.StatSerializer.serialize(StatSerializer.kt:34) ~[?:?]
	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.serialize(PlayerSerializer.kt:35) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.FlatFile.savePlayer(FlatFile.kt:42) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:51) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:18) ~[?:?]
	at me.ebonjaeger.perworldinventory.service.BukkitService$sam$java_lang_Runnable$0.run(BukkitService.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

cc: @CloudeLecaw

**Comment by Gnat008** [comment]
Fix released in RC2.
