### ISSUE TITLE
Losing Inventories

### ISSUE THREAD

**Issue by WalkingPixel1** [Gnat008/perworldinventory-kt#62]
When going to a creative that isnt the same group as the current survival world and then go back to survival world they lose their inventory for that current world has gone. Also they lose their enderchest items when moving to new world that isnt in the group.

latest Version this is from your plugin

**Comment by DalBrar** [comment]
This has been happening to me too so i've turned on debug msgs to try and catch the console log for Gnat

**Comment by medeman** [comment]
Yup, same for me.

The server logs show the following after switching the world (and the inventory is empty):

`issued server command: /mv tp alexworld
[23:47:38 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.1.0 generated an exception while executing task 87205
java.lang.NoSuchFieldError: PLAYER_HEAD
        at me.ebonjaeger.perworldinventory.serialization.ItemSerializer.serialize(ItemSerializer.kt:49) ~[?:?]
        at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.serializeInventory(InventorySerializer.kt:43) ~[?:?]
        at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.serializeAllInventories(InventorySerializer.kt:23) ~[?:?]
        at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.serialize(PlayerSerializer.kt:34) ~[?:?]
        at me.ebonjaeger.perworldinventory.data.FlatFile.savePlayer(FlatFile.kt:44) ~[?:?]
        at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:59) ~[?:?]
        at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:20) ~[?:?]
        at me.ebonjaeger.perworldinventory.service.BukkitService$sam$java_lang_Runnable$0.run(BukkitService.kt) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]`

Spigot Minecraft 1.12.2
